In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [24]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #independent variables form col. 3 (credit score) till the penultimate column
y = dataset.iloc[:, -1].values #last column containing the dependent variable

In [25]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [26]:
print(y)

[1 0 1 ... 1 1 0]


In [27]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [28]:
#encoding the categorical 'gender' data
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [29]:
#One hot encoding for the 'geography' column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [30]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [31]:
#splitting the data into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [32]:
#Apply feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
#fully connected ann containing a sequence of layers, starting with input layer, neuron and output layer
ann = tf.keras.models.Sequential() 

In [34]:
#adding input layer and first hidden layer with rectifier activation function
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [35]:
#adding second hidden layer (deep nn) with rectifier activation function
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

In [38]:
#adding the output layer with sigmoid activation function, as it gives a binary outcome and probability of outcome
#for non-binary use 'softmax'
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [39]:
#compile the ann using the 'adam' optimizer and loss function 'binary_crossentropy'
#as this is a binary outcome. For non-binary use 'categorical_crossentropy'
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [40]:
#For training an ann use the fit method, default is 32 for batch learning, and epochs (iterations on the training set) to learn properly and get prediction
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5960 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4726 - accuracy: 0.7990
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4221 - accuracy: 0.8188
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3907 - accuracy: 0.8376
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3683 - accuracy: 0.8504
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3597 - accuracy: 0.8501
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3556 - accuracy: 0.8512
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3534 - accuracy: 0.8526
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3525 - accuracy: 0.8521
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3515 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.3401 - accuracy: 0.8612
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8611
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8589
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3399 - accuracy: 0.8606
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8587
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8590
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3400 - accuracy: 0.8601
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8604
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3400 - accuracy: 0.8619
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3397 - accuracy: 

In [41]:
#Predicting the result of a single observation
#Geography: France
#Credit Score: 600
#Gender: Male
#Age: 40 years old
#Tenure: 3 years
#Balance: $ 60000
#Number of Products: 2
#Does this customer have a credit card? Yes
#Is this customer an Active Member: Yes
#Estimated Salary: $ 50000
#So, will that customer leave the bank?
# the output will be a probability so if you want to convert it to prediction, add >0.5; anything beyond that is true else false)
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [42]:
#predicting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [44]:
#making the confusion matrix to get the accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 197  208]]


0.8635